#ifndef Z1_SAMPLER_DEFAULTS_H
#define Z1_SAMPLER_DEFAULTS_H

#define SENSOR_INTERVAL 120
#define SENSOR_AVRIDS_COUNT 0
#define SENSOR_HASADC1 0
#define SENSOR_HASADC2 0
#define SENSOR_HASRAIN 0

#endif
