MKL25ZRF =  

CONTIKI_TARGET_DIRS = $(CONTIKI)/dev/cc1120 $(CONTIKI)/core/net

CFLAGS+= -DWITH_UIP6 -DUIP_CONF_IPV6 -DAUTOSTART_ENABLE 

MCK = 48000000
#CPLATFLAGS +=  
#PCFLAGS += -I$(CONTIKI)/dev/cc1120 -DCC11xx_CC1120=1 

CONTIKI_TARGET_SOURCEFILES += contiki-main.c cc1120-config.c cc1120-mkl25z-rf-arch.c cc1120.c

MODULES += core/net core/net/mac core/net/mac/contikimac core/net/llsec

include $(CONTIKI)/cpu/arm/mkl25z/Makefile.mkl25z



